### ISSUE TITLE
Adding rclone output logs in healthcheck.

### ISSUE THREAD

**Issue by dantebarba** [pfidr34/docker-rclone#25]
Healthcheck.io now supports attaching logs using HTTP POST instead of GET: https://healthchecks.io/docs/attaching_logs/
Logs are sliced to a limit of 10KB.

It would be cool if this could be added to the daemon, specially for failure cases (but it would be great for both success and failure too). It shouldn't be that hard, just using curl and post we could strip the last 10KB of the rclone.log file and appended as raw_data to the request sent afterwards.

**Comment by pfidr34** [comment]
@dantebarba thanks for submitting this request. It is complete, checked in and uploaded to DockerHub.

Success works as you described where I take the trailing 10KB from the log if it exists and send it as post data, else just `SUCCESS`.

See sample:
```
2020/08/31 16:31:00 INFO  : Starting bandwidth limiter at 200kBytes/s
2020/08/31 16:31:03 INFO  : TEST DIR.txt: Copied (new)
2020/08/31 16:31:03 INFO  : 
Transferred:   	         0 / 0 Bytes, -, 0 Bytes/s, ETA -
Transferred:            1 / 1, 100%
Elapsed time:         3.0s
```

In the event of a failure, one of two things will happen.

1.) If the failure was due to a failure from GoogleDrive, etc. and logged to the log file, the output will be as it was above.
2.) If it was some sort of hard failure within the container it will report failure with the message `Check container logs`.

**Comment by dantebarba** [comment]
wow that was fast, kudos!.
